spring:
  datasource:
    url: jdbc:mysql://localhost:3306/swifteats_customer?createDatabaseIfNotExist=true
    username: root
    password:  {cipher}eeda20d463b18275413fc0783fbf17a3fcb5b538520fcc504deaf05a7137135b
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  welcome-message: "Welcome Customer"
